### ISSUE TITLE
BUG: numbers are zeroed out

### ISSUE THREAD

**Issue by bsipocz** [barentsen/fsspec-monitor#1]
Not sure it's worth investigating, but run into this while I was showing the https://github.com/astropy/astropy/pull/13238 as an example to someone. Clearly, something is fishy with the printout, but I'm also worried about the progress bar and "download", which I'll make a note about in the main PR:

```
In [1]: from fsspecmonitor import FsspecMonitor  # requires `barentsen/fsspec-monitor`
   ...: from astropy.io import fits
   ...: 
   ...: # URL of a 213 MB Hubble image
   ...: url = "https://mast.stsci.edu/api/v0.1/Download/file/?uri=mast:HST/product/j8pu0y010_drc.fits"
   ...: 
   ...: with FsspecMonitor() as monitor:
   ...:     with fits.open(url, fsspec_kwargs={"block_size": 500_000}) as hdul:
   ...:         cutout = hdul[2].section[10:20, 30:40]
   ...:     monitor.summary()
   ...: 
Downloading https://mast.stsci.edu/api/v0.1/Download/file/?uri=mast:HST/product/j8pu0y010_drc.fits
|==================================================================================| 224M/224M (100.00%)         5s
Summary: fetched 0 bytes (0.00 MB) in 0.00 s (inf MB/s) using 0 requests.
```

**Comment by bsipocz** [comment]
Never mind me, this is the classic case of spotting the user error right after opening the issue.

If this tool would be distributed, maybe a note in the Summary would be nice that states that fsspec is not being used in the code.

**Comment by barentsen** [comment]
This is valuable user feedback. Perhaps we can make the output say:
```
Summary: fsspec fetched 0 bytes ...
```
instead of
```
Summary: fetched 0 bytes ...
```

... to make it more explicit that we only monitor bytes flowing via fsspec!

**Comment by bsipocz** [comment]
Or check if all numbers are 0 and say "fsspec was not used for this download" or similar.  Either case, it's not really critical, the bug was the user this time :)
